// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// League
export const START_LOADING_LEAGUE = 'START_LOADING_LEAGUE';
export const GET_LEAGUES = 'GET_LEAGUES';
export const GET_LEAGUES_FAILED = 'GET_LEAGUES_FAILED';
export const GET_LEAGUE = 'GET_LEAGUE';
export const GET_LEAGUE_FAILED = 'GET_LEAGUE_FAILED';
export const UPDATE_LEAGUE = 'UPDATE_LEAGUE';
export const UNMOUNT_LEAGUE = 'UNMOUNT_LEAGUE';

// Team
export const START_LOADING_TEAM = 'START_LOADING_TEAM';
export const GET_TEAMS = 'GET_TEAMS';
export const GET_TEAMS_FAILED = 'GET_TEAMS_FAILED';
export const GET_TEAM = 'GET_TEAM';
export const GET_TEAM_FAILED = 'GET_TEAM_FAILED';
export const UNMOUNT_TEAM = 'UNMOUNT_TEAM';

//Admin
export const LOADING_ADMIN = 'LOADING_ADMIN';
export const GET_DETAILS = 'GET_DETAILS';
export const GET_DETAILS_FAILED = 'GET_DETAILS_FAILED';
export const GET_ZONES = 'GET_ZONES';
export const GET_ZONES_FAILED = 'GET_ZONES_FAILED';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
export const GET_PHASES = 'GET_PHASES';
export const GET_PHASES_FAILED = 'GET_PHASES_FAILED';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';
export const UNMOUNT_ADMIN = 'UNMOUNT_ADMIN';
